"""
Injects 200-300 word technical descriptions (sourced from docs.nexthink.com)
into the 'description' column of the foundation_features sheet.

Run once:
    python3 update_feature_descriptions.py
"""
from openpyxl import load_workbook
from pathlib import Path

WB_PATH = Path("platform_content.xlsx")

DESCRIPTIONS = {
    "f_collect_endpoint": (
        "The Nexthink Collector is a lightweight agent implemented as a kernel-mode driver "
        "with accompanying user-space service modules, installed on Windows and macOS endpoints. "
        "On Windows the kernel component is signed with a Microsoft-issued certificate; on macOS "
        "the agent holds an Apple Developer ID and passes Apple notarisation. The driver intercepts "
        "OS-level events directly at the kernel layer, capturing network connections made by "
        "applications that use kernel-mode networking — traffic invisible to user-space monitors. "
        "Each functional concern is handled by a dedicated module: device performance monitoring, "
        "network connectivity tracking, user session recording, software inventory, employee "
        "engagement delivery, and remote action execution. The Collector samples device state every "
        "20–30 seconds and aggregates readings into 5- or 15-minute time slices before transmitting "
        "them to Nexthink's cloud infrastructure over an encrypted TCP channel. If connectivity is "
        "lost, the agent buffers up to 15 minutes of event packets (capped at 2,500 packets) in "
        "memory and retries; for persistent telemetry such as software inventory events, local disk "
        "persistence guarantees delivery for up to 7 days. Configuration changes and version updates "
        "are applied without an OS restart and without interrupting end-user sessions. The agent "
        "operates with negligible CPU and memory overhead, transmitting aggregated structured payloads "
        "rather than raw packet captures."
    ),
    "f_network": (
        "Network data collection in Nexthink is performed by the Collector kernel driver running on "
        "each endpoint. Because the driver operates at the kernel layer, it observes both user-space "
        "and kernel-mode network activity, capturing outgoing TCP connections and UDP datagrams "
        "invisible to user-space tools. For each connection, the Collector records the destination IP "
        "address, port, protocol, bytes transferred, and owning process. DNS resolution is tracked at "
        "the OS resolver level: when an application calls the OS DNS API, the Collector correlates the "
        "resolved domain name with subsequent connections, attaching the human-readable hostname to each "
        "connection event. If an application bypasses the OS resolver, the domain is not reported unless "
        "it can be retrieved from the TLS Server Name Indication (SNI) field. All captured data is "
        "stored in the NQL connection.events table, enabling queries across TCP initiation times, "
        "durations, volumes, and error codes. The Collector sampling cycle runs every 20–30 seconds and "
        "aggregates connection activity into 5-minute or 15-minute time slices before transmitting "
        "them to the Nexthink cloud backend. A change in network interface — such as switching from "
        "Wi-Fi to Ethernet — does not interrupt collection; the Collector adapts transparently. Network "
        "data is correlated server-side with application and device telemetry, enabling queries that "
        "link network errors directly to specific processes, users, and device configurations."
    ),
    "f_collabex": (
        "Nexthink Collaboration Experience collects call-quality data by connecting to the Microsoft "
        "Teams and Zoom vendor APIs via dedicated inbound connectors configured in the Nexthink "
        "administration console. For Microsoft Teams, the connector is granted the application "
        "permission CallRecords.Read.All against the Microsoft Graph API, pulling the full callRecord "
        "object for every completed call or online meeting across the tenant. For Zoom, the connector "
        "is scoped to meeting:read:admin and dashboard_meetings:read:admin, retrieving per-participant "
        "statistics including audio jitter, packet loss, latency, and video and screen-share quality "
        "scores from two Zoom API endpoints. Nexthink ingests this vendor telemetry and stores it in "
        "the NQL data model under the collaboration namespace, joined server-side with endpoint "
        "telemetry collected by the Collector on each participant's device — including CPU load, memory "
        "pressure, network interface state, and driver events recorded during the same time window. A "
        "unified call.quality metric is computed from the combined signal set, classifying each "
        "participant session as good, poor, or unclassified. Collaboration Experience dashboards surface "
        "call quality trends at organisational, group, device, and individual call levels. A correlations "
        "view groups users experiencing poor quality by location, device model, hardware peripheral, or "
        "network profile, enabling IT teams to identify whether a quality issue is systemic or isolated."
    ),
    "f_collect_sentiment": (
        "Nexthink Engage delivers in-context employee surveys — called Campaigns — through the Collector "
        "agent already running on the endpoint. The Collector's engagement module renders lightweight "
        "survey prompts directly on the employee's desktop as native or web-based notification popups, "
        "without requiring a separate application. Campaign triggers are evaluated on a schedule, based "
        "on a detected device or application event, or via an external HTTP API call from a third-party "
        "system. Event-based triggers are evaluated against NQL conditions: a campaign fires when the "
        "Collector reports that a device boot time has exceeded a threshold, or when a specific "
        "application crash event is recorded. When the trigger condition is met, the backend dispatches "
        "the campaign payload to the corresponding Collector agents. The payload can include dynamic "
        "parameters derived from the triggering event, making each prompt contextually specific to the "
        "recipient's situation. Employees respond to one or more questions — rating scales, multiple "
        "choice, or free text — within the desktop notification. Responses are transmitted back to the "
        "Nexthink cloud in real time and stored alongside the technical telemetry record that triggered "
        "the campaign. In the analytics layer, response data is correlated with device performance "
        "metrics, enabling cross-reference of subjective experience ratings with objective indicators "
        "such as crash frequency, application load time, or network error rates."
    ),
    "f_collect_external": (
        "Nexthink integrates with third-party IT systems through a two-directional connector framework "
        "consisting of inbound connectors, outbound connectors, and connector Thinklets. Inbound "
        "connectors pull data from external platforms into the Nexthink data model on a scheduled or "
        "event-driven basis. The Microsoft Entra ID connector authenticates via OAuth 2.0 against the "
        "Microsoft Graph API and imports identity attributes — department, manager, job title, group "
        "membership — mapped onto device and user records in NQL. The Microsoft Intune connector uses "
        "the Graph API to retrieve device compliance state, enrollment status, and policy assignments. "
        "The ServiceNow Incidents inbound connector synchronises incident records, enabling correlation "
        "of open tickets with device health data. Outbound connectors push Nexthink data to external "
        "systems. The webhook engine evaluates NQL alert conditions continuously; when a condition is "
        "met, it constructs an HTTP POST payload and delivers it to a configured REST endpoint — "
        "automatically opening a ServiceNow incident or updating a Jira ticket. The HTTP API Exporter "
        "extends this with scheduled bulk exports: administrators define NQL queries that select device, "
        "user, software, or connection records, and the exporter serialises results to external REST "
        "APIs, including the ServiceNow CMDB. Connector credentials are stored centrally in the "
        "Nexthink administration console and referenced by name in connector and webhook configurations."
    ),
    "f_corr_ai": (
        "Nexthink AI Insights operates as an analysis layer built on top of the telemetry platform, "
        "using large language models deployed within an AWS-hosted environment in the customer's "
        "geographical region — no data crosses that regional boundary. When a user opens an AI Insights "
        "surface, the platform executes a multi-step pipeline. In the data collection step, relevant "
        "telemetry slices are assembled: device performance metrics, application crash records, VDI "
        "session statistics, network error logs, and employee sentiment scores for the target scope and "
        "time window. In the AI processing step, this structured context is passed to the LLM along "
        "with a task-specific prompt that instructs the model to identify trends, classify topic "
        "clusters, detect anomalies, or rank contributing factors. The model's output is post-processed "
        "into structured summaries, anomaly flags, and ranked recommendations rendered in the Nexthink "
        "UI. For anomaly detection, Nexthink cross-references endpoint telemetry against anonymised "
        "aggregated signals drawn from over 15 million endpoints under management globally, enabling "
        "statistical outlier detection that compares a customer's observed metric distributions against "
        "the broader Nexthink fleet baseline. Specific anomaly types include latency spikes and slow "
        "login sequences in VDI sessions, CPU and memory anomalies correlated with binary versions or "
        "configurations, and application crash rate deviations. All LLM inference occurs entirely within "
        "the customer's regional AWS environment."
    ),
    "f_corr_dex_score": (
        "The DEX Score is a composite metric computed daily by the Nexthink platform to quantify the "
        "overall digital experience of employees. It is structured as a weighted combination of two "
        "top-level scores: a Technology score and a Sentiment score. The Technology score is itself "
        "composed of three subscores — Endpoint, Applications, and Collaboration — each derived from "
        "hard metrics collected by the Collector agent on employee devices. The Endpoint subscore "
        "reflects device reliability and performance, measuring indicators such as system boot times, "
        "crash frequencies, and OS stability. The Applications subscore captures the smoothness and "
        "response times of business applications. The Collaboration subscore measures the quality of "
        "tools such as Microsoft Teams and Zoom. Each subscore is calculated once per day at 00:00 UTC "
        "based on data aggregated over a rolling seven-day window, producing a value between 0 and 100. "
        "The Sentiment score is collected through a dedicated DEX campaign delivered to employees via "
        "the Collector, using only replies received within the last 30 days. The platform maps all "
        "final scores to three experience bands: Frustrating (0–30), Average (31–70), and Good "
        "(71–100). Score values are surfaced in the Infinity portal through the Digital Experience "
        "Overview dashboard and are queryable via NQL from the dedicated DEX score tables, enabling "
        "filtering and segmentation by device, user, location, or organisational unit."
    ),
    "f_act_dashboards": (
        "Nexthink Live Dashboards is a drag-and-drop dashboard builder embedded in the Infinity portal "
        "that constructs custom data visualisations using Nexthink Query Language (NQL) as the data "
        "retrieval layer. Each widget is backed by an NQL query that executes against the platform "
        "data store at render time, returning aggregated or raw records from any namespace — devices, "
        "users, applications, connections, alerts, and more. The builder supports multiple widget types "
        "including tables, bar charts, line charts, pie charts, scorecards, and geographic maps. "
        "Dashboards are classified into two modes: operational dashboards, which query high-resolution "
        "event data with retention of up to eight days, and reporting dashboards, which query trend "
        "data aggregated into one-day or seven-day samples stored for up to 13 months. Trend data is "
        "first defined through a separate Custom Trend NQL definition that stores aggregations in the "
        "platform, then a widget-level NQL definition surfaces that stored data — separating collection "
        "from presentation to reduce compute overhead. Newly created dashboards are private by default "
        "and can be shared with specific users or roles. Dashboards can be imported and exported as "
        "JSON packages, and pre-built dashboards ship with Library Packs. Operators can apply NQL-based "
        "filters at the dashboard level to scope all widgets simultaneously, and individual widgets "
        "support click-through drill-down that launches an Investigation scoped to the selected "
        "data point."
    ),
    "f_investigations": (
        "Investigations in Nexthink Infinity is an ad hoc query interface powered by the Nexthink "
        "Query Language (NQL), a purpose-built read-only query language operating against the "
        "platform's central data store. NQL uses a namespace-and-table data model that mirrors the "
        "structure of data collected by the Collector: primary namespaces include device, user, "
        "application, connection, execution, alert, campaign, and agent, each containing typed fields. "
        "The Collector continuously captures hardware inventory, software installation events, process "
        "executions, network connections, crashes, logon events, and performance counters, streaming "
        "this telemetry to the cloud-hosted data platform. Every NQL query begins with a FROM-style "
        "table declaration, followed by optional filter, aggregation, grouping, and ordering clauses, "
        "with a maximum query length of 16,000 characters. High-resolution event tables such as "
        "execution.events and connection.events retain data for up to eight days; entity and aggregated "
        "tables retain data for 30 days; trend tables hold up to 13 months. Queries execute in the "
        "NQL editor within the Investigations module and return results in near real time. Tables can "
        "be joined to correlate data across namespaces — for example, linking device performance data "
        "with user identity and application usage in a single query. NQL also underpins widget "
        "definitions in Live Dashboards, campaign audience targeting, alert monitor conditions, and "
        "data exporter payloads, making it the unified query layer across the entire platform."
    ),
    "f_act_remediation": (
        "Remote Actions allows IT teams to execute scripts on managed endpoints through the Collector "
        "agent without requiring direct network access or physical presence. Scripts are authored in "
        "PowerShell on Windows and Shell or Python on macOS, and must be signed with either a "
        "Nexthink-issued certificate or a company certificate listed in the device's Trusted Publishers "
        "store before the Collector will execute them. When a remote action is triggered, the platform "
        "pushes the signed script payload to the Collector on the targeted device; the Collector "
        "validates the signature and runs the script according to the device's PowerShell execution "
        "policy, then captures declared output variables and writes them back to the Nexthink data "
        "layer, where they become queryable via NQL and visible on dashboards. Remote actions can be "
        "triggered manually from the Investigations or device detail views, on a scheduled basis "
        "defined by an NQL query, via the Nexthink public REST API, or as a Thinklet within an "
        "automated Workflow. The Remote Action Thinklet in Workflows supports parameterised execution, "
        "allowing dynamic values from the workflow context to be passed as script inputs. Workflows "
        "chain multiple Thinklets — including remote actions, campaigns, and conditional logic — into "
        "multi-step automated remediation pipelines triggered by alerts or external events."
    ),
    "f_act_campaign": (
        "Nexthink Campaigns is a bidirectional communication system that delivers interactive "
        "notifications to employees via the Collector agent on their devices. When a campaign is "
        "published, the platform evaluates an NQL-defined target audience query to identify the set "
        "of users or user-device pairs that should receive it — starting from the users table for "
        "global targeting across all devices, or from the devices table to target users on specific "
        "devices with performance issues. The campaign payload is pushed from the platform to the "
        "Collector on each targeted device, which renders the notification in the bottom-right corner "
        "on Windows and top-right on macOS. Campaigns support multiple question types including "
        "opinion scales, multiple choice, and free text, and employees respond directly within the "
        "notification UI. Responses flow back to the platform and are stored in the campaign.responses "
        "table, queryable via NQL. Trigger models include Manual, Scheduled, Workflow-embedded, and "
        "API-triggered; the Scheduled trigger re-evaluates the NQL audience query every 24 hours so "
        "only employees who have not yet responded continue to receive the campaign. Urgent campaigns "
        "bypass focus protection and rate-limiting rules to ensure time-sensitive delivery. The "
        "Workflow trigger integrates campaigns as a Thinklet within automated remediation pipelines, "
        "enabling the platform to inform users of an ongoing action before or after a remote action "
        "executes. Campaign delivery and response data are also accessible programmatically through "
        "the Nexthink Campaigns REST API."
    ),
    "f_act_api": (
        "Nexthink exposes its data and capabilities to external systems through three integration "
        "mechanisms: a REST API, the HTTP API Exporter, and Webhooks. The Nexthink public REST API "
        "allows external applications to read platform data, trigger remote actions, fire campaigns, "
        "and query NQL programmatically over HTTPS using OAuth 2.0 bearer token authentication; this "
        "API is used to integrate Nexthink with ITSM platforms and chatbot frameworks. The HTTP API "
        "Exporter is a scheduled push mechanism that executes a configured NQL query on a defined "
        "interval and sends the resulting dataset to a target HTTP endpoint in batched JSON payloads; "
        "when a query returns more than 1,000 records, the platform segments results into batches of "
        "1,000 and dispatches them sequentially, up to one million records per run. A built-in "
        "throttling mechanism limits throughput to 3.33 batches per second to protect downstream "
        "systems from overload. Supported target systems include SIEMs such as Splunk, CMDB platforms, "
        "AIOps tools, monitoring pipelines, and Azure Event Hubs. Webhooks are event-driven outbound "
        "connectors that fire an HTTP POST to a configured URL whenever a specified Nexthink event "
        "occurs, such as an alert threshold breach or a campaign response. Each webhook is configured "
        "with an HTTP method, a resource path, and a JSON payload template. Credentials for all "
        "outbound connectors are managed centrally through the Connector Credentials store."
    ),
    "f_gov_rbac": (
        "Nexthink Infinity implements role-based access control through a layered permission model "
        "administered from Account Management. Each role carries two distinct configurations: a "
        "permissions set and a view domain. The permissions set defines what a user can do at both "
        "feature and content levels, including viewing dashboards, editing NQL investigations, "
        "triggering remote actions, managing campaigns, and accessing administrative functions such "
        "as creating connectors or managing licences. The view domain defines the data scope a role "
        "can see — scoped to specific entities, regions, or departments, or granting full access. "
        "Administrator accounts retain rights to create and manage users, assign roles, configure the "
        "platform, and manage the licence. The audit trail captures all administrative actions "
        "performed within the platform. Each auditable event is assigned a standardised code covering "
        "user creation, modification, deletion, role assignment, permission grant, and revocation. "
        "Audit log data is queryable directly via NQL and can be exported to third-party SIEM and "
        "IT Ops systems via the HTTP API Exporter, which supports batched delivery at up to 3.33 "
        "batches per second. The platform is hosted on AWS across multiple geographic regions, "
        "including EU, UK, US, UAE, Switzerland, and Australia. Customers select a single region at "
        "deployment time to satisfy data residency requirements. All AI model processing via Nexthink "
        "Assist is also confined to the AWS region aligned with the customer deployment. Data at rest "
        "is encrypted using AES-256 with an additional unique encryption key layer applied by Nexthink."
    ),
    "f_ai_tools": (
        "Nexthink AI Tools monitoring collects and aggregates AI application usage data from three "
        "complementary sources, surfacing the combined dataset through dedicated dashboards in the "
        "Infinity platform. The first source is the Collector agent at version 25.5.1 or later, "
        "which captures focus_time telemetry indicating when an employee is actively interacting with "
        "a foreground desktop application; for desktop-based AI tools, focus_time is used to estimate "
        "AI-engaged time. The second source is the Nexthink browser extension at version 25.8.1 or "
        "newer, which tracks web-based AI tool usage in supported browsers. The third source is a "
        "purpose-built inbound connector for Microsoft Copilot, which ingests usage event data for "
        "Copilot across Microsoft 365 applications. The Microsoft Entra ID connector runs in parallel "
        "to retrieve user licence data and tag each Copilot interaction as originating from a free or "
        "licensed account. AI-engaged time is computed in 15-minute intervals: any number of "
        "interactions within a single 15-minute bucket counts as exactly 15 minutes. The system "
        "aggregates data weekly and segments employees into four behavioural quadrants based on "
        "engagement time and frequency: Champions, Deep Divers, Regulars, and Explorers. Dashboards "
        "display week-over-week trends, a heatmap of engagement by department and application, tool "
        "adoption rates, and sentiment feedback collected via built-in Collector campaigns. "
        "Administrators configure which AI tools to track through the AI Tools configuration interface."
    ),
    "f_spark": (
        "Nexthink Spark is an agentic AI resolution engine embedded within the Infinity platform that "
        "enables employees to resolve IT issues autonomously through natural language interaction. "
        "Employees interact with Spark through a chat interface accessible directly on their endpoint "
        "device. When an employee submits a problem description, Spark interprets the intent using an "
        "AI language model and maps it to a resolution workflow. The engine queries live DEX telemetry "
        "from the Nexthink platform — including real-time device configuration, application performance "
        "data, and endpoint state — to evaluate the most likely root cause. Based on this diagnosis, "
        "Spark selects from a library of IT-approved actions in two categories: diagnostic actions, "
        "which collect real-time information about device state, and remediation actions, which apply "
        "direct fixes such as resetting application settings or clearing caches. All actions are "
        "pre-approved and governed by IT administrators who configure which actions Spark is permitted "
        "to execute. Spark stores a contextId and taskId per conversation to maintain session "
        "continuity across multi-turn interactions. IT teams can integrate Spark into existing "
        "conversational platforms such as ServiceNow or Microsoft Teams using the Agent-to-Agent API, "
        "which uses an OAuth client credential flow against the Spark A2A REST API endpoint, or the "
        "Spark Handoff API for non-A2A-capable chatbots. NQL-based data model tables store "
        "Spark-user interaction logs, making conversation and resolution data queryable for IT "
        "analytics. Each user is identified by their userPrincipalName passed in API request metadata."
    ),
    "f_mobile": (
        "Nexthink Mobile Experience extends the Infinity platform's monitoring capabilities to iOS "
        "and Android devices through a lightweight native mobile application and integration with "
        "Unified Endpoint Management solutions. The Nexthink Mobile app is distributed via the Apple "
        "App Store and Google Play Store, or deployed silently through a UEM tool using managed app "
        "configuration. Once installed, the app runs continuously in the background and collects "
        "telemetry at regular intervals, transmitting updates to the Nexthink Infinity backend "
        "approximately every 15 minutes. The app captures device-level metrics including battery "
        "health, network connectivity stability, operating system version, storage state, and "
        "application performance data. This telemetry is sent directly to the customer's regional "
        "Nexthink cloud instance. In parallel, the Microsoft Intune connector for Mobile Devices "
        "optionally pulls compliance and enrollment data, including data from BYOD devices on which "
        "the Nexthink app cannot be installed. The combined dataset from the app and UEM connectors "
        "is stored in dedicated NQL data model tables containing fields for hardware specifications, "
        "OS details, network state, application data, and MDM supervision status. IT administrators "
        "query this data using NQL in any investigation-enabled surface within Infinity. A dedicated "
        "Mobile Device Monitoring dashboard aggregates the collected metrics and provides "
        "visualisations of fleet health, OS adoption, battery degradation, and connectivity issues, "
        "with full customisation to surface the metrics most relevant to the organisation."
    ),
    "f_workspace": (
        "Nexthink Workspace is the conversational AI interface for IT operators within the Infinity "
        "platform, powered by the Nexthink Assist AI model. It provides a persistent, context-aware "
        "chat environment through which IT teams can investigate environment conditions, retrieve "
        "device and user data, analyse application performance, and initiate platform actions using "
        "natural language prompts. When a user submits a query, Nexthink Assist interprets the "
        "request using an AWS-hosted AI model, then selects one or more tools to fulfil the request: "
        "running NQL queries against the data platform, consulting indexed Nexthink documentation, "
        "generating campaigns, or retrieving configuration objects. When a visualisation is requested, "
        "the system automatically constructs and executes the appropriate NQL investigation, retrieves "
        "the resulting data, and renders a chart with contextual annotations. The AI model "
        "infrastructure runs on AWS Bedrock within the customer's geographic region, using a "
        "combination of off-the-shelf and fine-tuned large language models including Anthropic "
        "Claude, Meta CodeLlama, and other AWS Bedrock models. Conversations are stateful: Workspace "
        "retains the full thread of the ongoing session so follow-up questions are resolved in "
        "context. Sessions are automatically persisted for 30 days from the last activity. The system "
        "is scoped to the permissions of the authenticated user, meaning NQL queries and data "
        "returned through Workspace respect the view domain configured on the user's assigned roles."
    ),
    "f_exp_central": (
        "Experience Central is the strategic analytics module within Nexthink Infinity that aggregates "
        "and presents the Digital Employee Experience score alongside industry benchmarking data. At "
        "its core is the DEX score, a composite metric computed daily from two sub-scores: the "
        "Technology score and the Sentiment score. The Technology score is derived from Collector "
        "telemetry across three dimensions: Endpoint metrics covering hardware performance and OS "
        "health, Application metrics covering crashes, freezes, and responsiveness, and Collaboration "
        "tool metrics covering tools such as Microsoft Teams. The Sentiment score is produced from "
        "employee satisfaction survey responses collected via Nexthink Campaigns. The two sub-scores "
        "are merged into the overall DEX score surfaced in the Overview dashboard, with breakdowns by "
        "hardware model, OS version, department, and geographic entity. DEX score metrics are "
        "separated by device type to distinguish physical endpoints from VDI sessions, removing "
        "metrics irrelevant to virtual environments. The Benchmark dashboard provides industry "
        "comparison by querying a continuously maintained dataset of anonymised aggregated DEX metrics "
        "from the broader Nexthink customer base, refreshed weekly. Benchmark metrics are computed as "
        "mean values per device for most indicators and as median values per customer for Application "
        "Crashes and Freezes. The system assigns each organisation metric a label: Leading indicates "
        "performance more than 5 percent better than the selected industry cohort, Lagging more than "
        "5 percent worse, and Normal falls within the plus-or-minus 5 percent band."
    ),
    "f_amplify": (
        "Nexthink Amplify is a browser extension that embeds a contextual Nexthink intelligence "
        "widget directly inside any web-based IT service management tool, including ServiceNow Agent "
        "Workspace, ServiceNow Operations Workspace, and Jira. When an agent opens a ticket, Amplify "
        "uses configurable field selectors and URL pattern matching to extract device and user "
        "identifiers from the ITSM page DOM. Those identifiers are forwarded to the Nexthink backend, "
        "which returns real-time endpoint telemetry — hardware health, software events, network "
        "performance, and recent remote action history — rendered inside the Amplify sidebar panel "
        "without the agent leaving the ITSM interface. The inbound data flow is driven by the "
        "extension connecting to the Nexthink Infinity API using OAuth 2.0 connector credentials "
        "(Access token URL, Client ID, Client secret, and Scope). The outbound data flow is achieved "
        "through webhook configuration: after a support agent triggers a remote action or workflow "
        "from within the Amplify panel, Nexthink fires a configured webhook upon execution start "
        "and again upon completion, automatically appending result details to the ServiceNow incident "
        "ticket log or Jira comment thread. The webhook payload is structured to match the target "
        "ITSM object schema and is sent via HTTPS POST using the same connector credential. "
        "Administrators configure field selectors per web application URL pattern, enabling Amplify "
        "to support multiple ITSM instances and custom portals simultaneously."
    ),
    "f_library": (
        "The Nexthink Content Library is an online repository integrated into the Infinity platform "
        "from which administrators browse, install, and manage pre-built content packs called library "
        "packs. Each library pack is a versioned, self-describing bundle grouping related content "
        "items by use case — for example, a Citrix CVAD Essentials pack or a Wi-Fi Diagnostics pack. "
        "Content items within a pack can be of several types: NQL-based dashboards, monitors (alert "
        "definitions), remote actions (PowerShell or Bash scripts), campaigns (employee engagement "
        "surveys), and custom fields. Library packs expose metadata including description, version "
        "number, and inter-item dependencies, allowing the platform to validate that all prerequisites "
        "are present before installation. When an administrator clicks Install, the platform resolves "
        "dependencies and provisions all required objects into the tenant, making them immediately "
        "available for use. Role-based access control gates installation: deploying a pack containing "
        "remote actions requires the Manage all remote actions permission, while dashboards require "
        "Manage all dashboards. The library is maintained by Nexthink and updated independently of "
        "the core platform release cycle, meaning new packs and updated versions become available "
        "without a platform upgrade. Once installed, individual content items can be customised — for "
        "instance, editing monitor thresholds or modifying NQL queries — while retaining traceability "
        "to the original pack version, separating the delivery of operational knowledge from "
        "platform code."
    ),
    "f_appex": (
        "Nexthink Application Experience performs real-user monitoring of both web and desktop "
        "applications by collecting telemetry from the endpoint through the Collector agent and, for "
        "browser-based applications, through companion browser extensions installed on managed devices. "
        "For web applications, the browser extension instruments HTTP/HTTPS traffic and DOM events to "
        "capture page load timing, transaction durations, and reliability signals (error rates, failed "
        "requests) without requiring changes to application code or servers. Page loads measure the "
        "time from navigation initiation to the page being interactive, while transactions capture "
        "state changes within single-page applications that do not trigger a full navigation event. "
        "For desktop applications, the Collector observes process-level performance data including "
        "CPU usage, memory consumption, crashes, and hangs at the application binary level. All "
        "collected metrics are timestamped at the endpoint and streamed to the Nexthink cloud, stored "
        "in the NQL data model under objects such as web.page_views and web.events. The platform "
        "aggregates these events into three monitoring dimensions — page loads, transactions, and "
        "reliability — and refreshes application overview dashboards every five minutes, reranking "
        "application groups based on the latest computed values. NQL-based dashboards expose "
        "predefined drill-downs, and the system calculates a time-lost metric that converts raw "
        "performance degradation figures into estimated minutes of lost user productivity, combining "
        "page load delays, transaction slowdowns, and reliability failures into a single impact score."
    ),
    "f_vdi": (
        "Nexthink VDI Experience monitors virtual desktop sessions across Citrix Virtual Apps and "
        "Desktops (CVAD), Citrix DaaS, VMware Horizon, and Microsoft Azure Virtual Desktop (AVD) by "
        "deploying lightweight agents at two points in the session topology: on the virtual machine "
        "and on the client endpoint. On the VM side, the standard Nexthink Collector is installed "
        "and collects resource utilisation metrics — CPU, memory, disk I/O — as well as session-level "
        "events from the guest OS. On the client side, administrators deploy either the full Collector "
        "for company-managed devices or the VDI Client Extension, designed for personal or unmanaged "
        "endpoints. The VDI Client Extension communicates with the Collector running on the VM using "
        "a Dynamic Virtual Channel (DVC), a multiplexed sub-channel embedded within the existing "
        "remote display protocol session — ICA/HDX for Citrix, Blast or PCoIP for VMware Horizon, "
        "and RDP for AVD. No additional network ports or firewall rules are required; all VDI "
        "telemetry is tunnelled inside the already-established session protocol. The data collected "
        "via DVC includes client-side metrics such as endpoint hardware health, local network latency, "
        "and peripheral responsiveness, correlated server-side with VM-level metrics. For Citrix "
        "environments, an inbound connector queries the Citrix Monitoring API via the Director service "
        "and PowerShell SDK, retrieving broker-level session metadata including logon duration "
        "breakdowns. All session data is stored with 30-second time-bucket granularity for the most "
        "recent 48 hours."
    ),
    "f_alert": (
        "Nexthink Alerts are driven by monitors, which are scheduled evaluation rules that run NQL "
        "queries against collected endpoint and application telemetry at configurable intervals "
        "ranging from 15 minutes to 7 days. Each monitor defines an NQL query that must include at "
        "least one computed or aggregated metric using a compute or summarize clause; the resulting "
        "numeric output is evaluated against a trigger condition. Three trigger detection modes are "
        "supported. Metric threshold fires when a metric value crosses a static user-defined bound. "
        "Metric change fires when the current value deviates from a rolling 7-day global average by "
        "more than a configured percentage, providing relative anomaly detection without requiring "
        "knowledge of absolute normal values. Metric seasonal change fires when the current value "
        "falls outside a time-of-day-aware baseline derived from the same hourly slot across the "
        "prior seven days, with sensitivity governed by a standard deviation band — making the system "
        "aware of daily and weekly usage patterns such as Monday morning login surges. Built-in "
        "monitors additionally support an Events detection method that triggers in real time on raw "
        "event streams. When a monitor condition is met, the platform generates an alert record and "
        "can dispatch notifications via email or outbound webhook to external systems such as "
        "ServiceNow or Slack. Alert impact analysis augments each triggered alert using an LLM that "
        "evaluates affected device count, entity scope, and breached metric, producing a categorised "
        "impact assessment covering employee productivity, business operations, and IT workload."
    ),
    "f_diagnostic": (
        "When Nexthink triggers an alert, the platform automatically generates a Diagnostics page "
        "co-located with the alert record, providing a first-level root cause analysis without "
        "requiring manual investigation steps by the IT engineer. The Diagnostics page is composed "
        "of several auto-populated sections. At the top it displays the monitor name, the specific "
        "context entity that breached the threshold, and the primary monitored condition. A timeline "
        "panel visualises the metric trend around the alert event, enabling engineers to see whether "
        "the issue is isolated or part of a longer degradation pattern. The core of the automated "
        "analysis is a statistical insights engine that applies Bayesian inference to identify which "
        "device attributes — such as OS version, hardware model, installed software versions, network "
        "segment, or geographic location — are statistically over-represented among the affected "
        "devices compared to the unaffected population within the same tenant. The algorithm "
        "quantifies a likelihood score for each candidate attribute, ranking them from most to least "
        "probable contributor, so the first item in the insights list represents the strongest "
        "statistical differentiator. The engine supplements tenant-specific inference with anonymised "
        "cross-customer benchmarking data aggregated from Nexthink's cloud customer base, helping "
        "distinguish issues idiosyncratic to a specific environment from those following broader "
        "industry patterns. Engineers can apply filters by technical property, geographic location, "
        "or organisational entity directly on the Diagnostics page to narrow scope and validate "
        "hypotheses."
    ),
}

def main():
    wb = load_workbook(WB_PATH)
    ws = wb["foundation_features"]

    # Find header row and column indices
    header_row = None
    for r in range(1, ws.max_row + 1):
        cell = ws.cell(row=r, column=1)
        if cell.font and cell.font.bold and not cell.font.italic and cell.value:
            header_row = r
            break
    if header_row is None:
        raise SystemExit("Could not find header row in foundation_features")

    # Map column names to indices
    cols = {}
    for c in range(1, ws.max_column + 1):
        v = ws.cell(row=header_row, column=c).value
        if v:
            cols[str(v).strip()] = c

    if "id" not in cols or "description" not in cols:
        raise SystemExit(f"Missing expected columns. Found: {list(cols.keys())}")

    id_col  = cols["id"]
    desc_col = cols["description"]

    updated = 0
    for r in range(header_row + 1, ws.max_row + 1):
        fid = ws.cell(row=r, column=id_col).value
        if fid and str(fid).strip() in DESCRIPTIONS:
            ws.cell(row=r, column=desc_col).value = DESCRIPTIONS[str(fid).strip()]
            updated += 1

    wb.save(WB_PATH)
    print(f"OK → {WB_PATH}  ({updated} feature descriptions updated)")

if __name__ == "__main__":
    main()
